CREATE DATABASE database_links;
USE database_links;
CREATE TABLE USUARIO(
    id INT(11) NOT NULL,
    username varchar(16) NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullname varchar(100) NOT NULL
);

ALTER TABLE USUARIO
    ADD PRIMARY KEY(id);

ALTER TABLE USUARIO
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;


DESCRIBE USUARIO

CREATE TABLE LINKS
(
    id INT(11) NOT NULL,
    title VARCHAR(150) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT,
    user_id INT(11),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES USUARIO(id)
);


ALTER TABLE LINKS
    ADD PRIMARY KEY(id);

ALTER TABLE LINKS
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'password';